version: '3.5'
services:
  db:
    build: postgresql
    image: event-guide_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - event-guide_ntwrk
  pgadmin:
    build: pgadmin
    image: event-guide_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - event-guide_ntwrk
  swagger-ui:
    build: swagger-ui
    image: event-guide_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - event-guide_ntwrk

  event-film-service:
    build: event-film-service
    image: event-guide_film-service:1.0.0
    networks:
      - event-guide_ntwrk
  event-concert-service:
    build: event-concert-service
    image: event-guide_concert-service:1.0.0
    networks:
      - event-guide_ntwrk
  event-classifier-service:
    build: event-classifier-service
    image: event-guide_classifier-service:1.0.0
    networks:
      - event-guide_ntwrk
  event-user-service:
    build: event-user-service
    image: event-guide_user-service:1.0.0
    networks:
      - event-guide_ntwrk

  proxy:
    build: proxy
    image: event-guide_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - event-guide_ntwrk
networks:
    event-guide_ntwrk:
      name: event-guide_ntwrk