spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://db:5432/user_service
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 83
  error:
      include-message: ALWAYS