spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/film_service?currentSchema=main
    driver-class-name: org.postgresql.Driver
server:
  port: 80