spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/user_service
    driver-class-name: org.postgresql.Driver
server:
  port: 8083
  error:
      include-message: ALWAYS